name: minitwitter
services:
  load-balancer:
    container_name: load-balancer
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  postgres:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: minitwitter
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

  minitwitter-frontend:
    container_name: frontend
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      NUX_PubliC_API_BASE_URL: http://localhost:80

  minitwitter1:
    image: wotasoy/simple-api
    container_name: minitwitter1
    restart: always
    environment:
      DATABASE_URL: postgressql://postgres:supersecret123@my-postgres:5432/minitwitter
      command: /bin/sh -c "bunx drizzle-kit push && bun run prod"
    volumes:
      - ./docker-data/postgres_db:/var/lib/postgresql/data

  minitwitter2:
    image: wotasoy/simple-api
    container_name: minitwitter2
    restart: always
    environment:
      DATABASE_URL: postgressql://postgres:supersecret123@my-postgres:5432/minitwitter
      command: /bin/sh -c "bunx drizzle-kit push && bun run prod"
    volumes:
      - ./docker-data/postgres_db:/var/lib/postgresql/data